"""Distill EuroBERT-2.1B block classifier into EuroBERT-610m via all-position KL-div.

Phase 2: loads pre-computed teacher logits from disk (generated by generate_teacher_logits.py).

Loss = alpha * KL(teacher_soft || student_soft) + (1-alpha) * CE(student, hard_labels_at_sep)

Usage:
  # First run: python data/generate_teacher_logits.py --num-gpus 4
  # Then train:
  accelerate launch --num_processes 4 data/train_distill_eurobert.py --epochs 1
"""

import os
import sys
import time

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
import html2text
from collections import Counter
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    set_seed,
)
from sklearn.metrics import f1_score, precision_score, recall_score

# ── MinerU-HTML module loading ──
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MINERU_PATH = os.path.join(SCRIPT_DIR, '..', '..', 'MinerU-HTML')

import importlib.util
import re
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum

def _make_module(name):
    mod = type(sys)(name)
    sys.modules[name] = mod
    return mod

if 'mineru_html' not in sys.modules:
    _make_module('mineru_html')
    _c = _make_module('mineru_html.constants')
    _c.ITEM_ID_ATTR = '_item_id'
    _c.TAIL_BLOCK_TAG = 'cc-alg-uc-text'
    _c.SELECT_ATTR = 'cc-select'
    _c.CLASS_ATTR = 'mark-selected'

    class TagType(Enum):
        Main = 'main'
        Other = 'other'
    _c.TagType = TagType

    _e = _make_module('mineru_html.exceptions')
    class MinerUHTMLError(Exception): pass
    for cn in ['MinerUHTMLPreprocessError', 'MinerUHTMLPromptError',
               'MinerUHTMLResponseParseError', 'MinerUHTMLMapToMainError',
               'MinerUHTMLFallbackError']:
        setattr(_e, cn, type(cn, (MinerUHTMLError,), {}))
    _e.MinerUHTMLError = MinerUHTMLError

    _b = _make_module('mineru_html.base')
    @dataclass
    class MinerUHTMLProcessData:
        simpled_html: str = ''
        map_html: str = ''
    @dataclass
    class MinerUHTMLGenerateInput:
        full_prompt: str = ''
    @dataclass
    class MinerUHTMLParseResult:
        item_label: dict = field(default_factory=dict)
    @dataclass
    class MinerUHTMLOutput:
        main_html: str = ''
    @dataclass
    class MinerUHTMLInput:
        raw_html: str = ''
    @dataclass
    class MinerUHTMLCase:
        case_id: str = ''
        input_data: MinerUHTMLInput = field(default_factory=MinerUHTMLInput)
        process_data: MinerUHTMLProcessData = field(default_factory=MinerUHTMLProcessData)
        generate_input: MinerUHTMLGenerateInput = field(default_factory=MinerUHTMLGenerateInput)
        generate_output: Optional[object] = None
        parse_result: MinerUHTMLParseResult = field(default_factory=MinerUHTMLParseResult)
        output_data: MinerUHTMLOutput = field(default_factory=MinerUHTMLOutput)
    for cls in [MinerUHTMLCase, MinerUHTMLProcessData, MinerUHTMLGenerateInput,
                MinerUHTMLParseResult, MinerUHTMLOutput, MinerUHTMLInput]:
        setattr(_b, cls.__name__, cls)

    _make_module('mineru_html.process')

    def _load_file(mod_name, filename):
        path = os.path.join(MINERU_PATH, 'mineru_html', 'process', filename)
        spec = importlib.util.spec_from_file_location(mod_name, path)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[mod_name] = mod
        spec.loader.exec_module(mod)
        return mod

    _load_file('mineru_html.process.html_utils', 'html_utils.py')
    _load_file('mineru_html.process.simplify_html', 'simplify_html.py')
    _load_file('mineru_html.process.map_to_main', 'map_to_main.py')

simplify_html = sys.modules['mineru_html.process.simplify_html'].simplify_html
extract_main_html = sys.modules['mineru_html.process.map_to_main'].extract_main_html

from block_chunker import extract_blocks, tokenize_blocks, pack_chunks, SEP_TOKEN

# ── Config ──
TEACHER_PATH = os.path.join(SCRIPT_DIR, 'block_classifier_eurobert_2.1B', 'checkpoint-5250')
STUDENT_MODEL = "EuroBERT/EuroBERT-610m"
MAX_TOKENS = 8192
SEED = 42
ALPHA = 0.7
TEMPERATURE = 2.0

LOGITS_DIR = os.path.join(SCRIPT_DIR, 'teacher_logits_2.1B')
WMB_EVAL_PATH = os.path.join(SCRIPT_DIR, 'wmb_eval_sample.jsonl')
OUTPUT_DIR = os.path.join(SCRIPT_DIR, 'block_classifier_eurobert_610m_distill')

LABEL_OTHER = 0
LABEL_MAIN = 1
IGNORE_LABEL = -100
NUM_LABELS = 2


class DistillDataset(Dataset):
    """Loads teacher logits lazily from disk."""

    def __init__(self, indices, meta, logits_dir):
        self.indices = indices
        self.input_ids = meta['input_ids']
        self.labels = meta['labels']
        self.logits_dir = logits_dir

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        global_idx = self.indices[idx]
        teacher_logits = torch.load(
            os.path.join(self.logits_dir, f'{global_idx}.pt'),
            weights_only=True,
        ).float()
        return {
            'input_ids': self.input_ids[global_idx],
            'labels': self.labels[global_idx],
            'teacher_logits': teacher_logits,
        }


class DistillCollator:
    def __init__(self, pad_token_id):
        self.pad_token_id = pad_token_id

    def __call__(self, features):
        max_len = max(len(f['input_ids']) for f in features)

        input_ids = []
        attention_mask = []
        labels = []
        teacher_logits = []

        for f in features:
            seq_len = len(f['input_ids'])
            pad_len = max_len - seq_len
            input_ids.append(f['input_ids'] + [self.pad_token_id] * pad_len)
            attention_mask.append([1] * seq_len + [0] * pad_len)
            labels.append(f['labels'] + [IGNORE_LABEL] * pad_len)
            tl = f['teacher_logits']  # (seq_len, 2) tensor
            if pad_len > 0:
                tl = torch.cat([tl, torch.zeros(pad_len, 2)], dim=0)
            teacher_logits.append(tl)

        return {
            'input_ids': torch.tensor(input_ids, dtype=torch.long),
            'attention_mask': torch.tensor(attention_mask, dtype=torch.long),
            'labels': torch.tensor(labels, dtype=torch.long),
            'teacher_logits': torch.stack(teacher_logits),
        }


class DistillTrainer(Trainer):
    def __init__(self, alpha=0.7, temperature=2.0, **kwargs):
        super().__init__(**kwargs)
        self.alpha = alpha
        self.temperature = temperature

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop('labels')
        teacher_logits = inputs.pop('teacher_logits')
        attention_mask = inputs['attention_mask']

        outputs = model(**inputs)
        student_logits = outputs.logits

        mask = attention_mask.bool()
        T = self.temperature

        teacher_soft = F.log_softmax(teacher_logits / T, dim=-1)
        student_soft = F.log_softmax(student_logits / T, dim=-1)

        kl_per_token = F.kl_div(
            student_soft, teacher_soft, log_target=True, reduction='none'
        ).sum(dim=-1)

        kl_loss = (kl_per_token * mask.float()).sum() / mask.float().sum()
        kl_loss = kl_loss * (T * T)

        ce_loss = F.cross_entropy(
            student_logits.view(-1, student_logits.size(-1)),
            labels.view(-1),
            ignore_index=IGNORE_LABEL,
        )

        loss = self.alpha * kl_loss + (1 - self.alpha) * ce_loss
        return (loss, outputs) if return_outputs else loss


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    mask = labels != IGNORE_LABEL
    flat_preds = preds[mask]
    flat_labels = labels[mask]

    acc = (flat_preds == flat_labels).mean()
    f1 = f1_score(flat_labels, flat_preds, pos_label=LABEL_MAIN, zero_division=0)
    prec = precision_score(flat_labels, flat_preds, pos_label=LABEL_MAIN, zero_division=0)
    rec = recall_score(flat_labels, flat_preds, pos_label=LABEL_MAIN, zero_division=0)

    return {'accuracy': acc, 'f1': f1, 'precision': prec, 'recall': rec}


# ── Inference / Eval ──

def html_to_text(html_str):
    h = html2text.HTML2Text(bodywidth=0)
    h.ignore_links = True
    h.ignore_images = True
    return h.handle(html_str)


def ngrams(tokens, n):
    return [tuple(tokens[i:i+n]) for i in range(len(tokens) - n + 1)]


def rouge_n_f1(reference, prediction, n=5):
    ref_tokens = reference.split()
    pred_tokens = prediction.split()
    if not ref_tokens or not pred_tokens:
        return 0.0
    ref_ngrams = Counter(ngrams(ref_tokens, n))
    pred_ngrams = Counter(ngrams(pred_tokens, n))
    if not ref_ngrams or not pred_ngrams:
        return 0.0
    overlap = sum((ref_ngrams & pred_ngrams).values())
    precision = overlap / max(sum(pred_ngrams.values()), 1)
    recall = overlap / max(sum(ref_ngrams.values()), 1)
    if precision + recall == 0:
        return 0.0
    return 2 * precision * recall / (precision + recall)


@torch.no_grad()
def classify_page_chunked(model, tokenizer, sep_token_id, simplified_html, device):
    blocks = extract_blocks(simplified_html)
    if not blocks:
        return {}

    item_id_pattern = re.compile(r'_item_id="(\d+)"')
    block_item_ids = []
    for block in blocks:
        m = item_id_pattern.search(block)
        block_item_ids.append(m.group(1) if m else None)

    block_token_ids = tokenize_blocks(blocks, tokenizer)
    chunks = pack_chunks(
        block_token_ids, max_tokens=MAX_TOKENS,
        sep_token_id=sep_token_id,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )

    labels = {}
    for chunk_ids, chunk_block_indices in chunks:
        input_ids = torch.tensor([chunk_ids], dtype=torch.long, device=device)
        attn_mask = torch.ones_like(input_ids)
        outputs = model(input_ids=input_ids, attention_mask=attn_mask)
        logits = outputs.logits[0]
        sep_positions = (input_ids[0] == sep_token_id).nonzero(as_tuple=True)[0]
        preds = logits[sep_positions].argmax(dim=-1).cpu().tolist()
        for sep_idx, block_idx in enumerate(chunk_block_indices):
            if sep_idx < len(preds) and block_idx < len(block_item_ids):
                item_id = block_item_ids[block_idx]
                if item_id is not None:
                    labels[item_id] = 'main' if preds[sep_idx] == LABEL_MAIN else 'other'
    return labels


def eval_rouge5_on_wmb(model, tokenizer, sep_token_id, device, wmb_records):
    import json
    model.eval()
    scores = []
    scores_by_level = {}
    empty = 0

    for rec in wmb_records:
        html_content = rec.get('html', '')
        reference = rec.get('convert_main_content', '')
        level = rec.get('meta', {}).get('level', 'unknown')

        if not html_content or not reference:
            scores.append(0.0)
            scores_by_level.setdefault(level, []).append(0.0)
            continue

        try:
            simplified, map_html = simplify_html(html_content)
        except Exception:
            scores.append(0.0)
            scores_by_level.setdefault(level, []).append(0.0)
            continue

        labels = classify_page_chunked(model, tokenizer, sep_token_id, simplified, device)

        n_main = sum(1 for v in labels.values() if v == 'main')
        if n_main == 0:
            pred_text = ''
        else:
            try:
                main_html = extract_main_html(map_html, labels)
                pred_text = html_to_text(main_html).strip()
            except Exception:
                pred_text = ''

        if not pred_text:
            empty += 1
            r5 = 0.0
        else:
            r5 = rouge_n_f1(reference, pred_text, n=5)

        scores.append(r5)
        scores_by_level.setdefault(level, []).append(r5)

    avg = sum(scores) / max(len(scores), 1)
    level_avgs = {}
    for lev in ['simple', 'mid', 'hard']:
        vals = scores_by_level.get(lev, [])
        level_avgs[lev] = sum(vals) / max(len(vals), 1)

    return avg, level_avgs, empty


class RougeEvalCallback(TrainerCallback):
    def __init__(self, tokenizer, sep_token_id, wmb_records):
        self.tokenizer = tokenizer
        self.sep_token_id = sep_token_id
        self.wmb_records = wmb_records

    def on_evaluate(self, args, state, control, model=None, **kwargs):
        if args.local_rank > 0:
            return
        if not self.wmb_records:
            return
        device = next(model.parameters()).device
        avg, level_avgs, empty = eval_rouge5_on_wmb(
            model, self.tokenizer, self.sep_token_id, device, self.wmb_records,
        )
        print(f'\n  WMB ROUGE-5 (step {state.global_step}, {len(self.wmb_records)} pages):  '
              f'All={avg:.4f}  Simple={level_avgs["simple"]:.4f}  '
              f'Mid={level_avgs["mid"]:.4f}  Hard={level_avgs["hard"]:.4f}  '
              f'Empty={empty}', flush=True)


def main():
    import argparse
    import json
    parser = argparse.ArgumentParser()
    parser.add_argument('--epochs', type=int, default=1)
    parser.add_argument('--batch-size', type=int, default=4)
    parser.add_argument('--grad-accum', type=int, default=2)
    parser.add_argument('--lr', type=float, default=2e-5)
    parser.add_argument('--alpha', type=float, default=ALPHA)
    parser.add_argument('--temperature', type=float, default=TEMPERATURE)
    parser.add_argument('--val-chunks', type=int, default=1000)
    args = parser.parse_args()

    set_seed(SEED)
    local_rank = int(os.environ.get('LOCAL_RANK', -1))
    is_main = local_rank <= 0

    if is_main:
        print(f'=== EuroBERT Distillation: 2.1B → 610m (Phase 2: Train) ===', flush=True)
        print(f'  Alpha (KL weight): {args.alpha}', flush=True)
        print(f'  Temperature: {args.temperature}', flush=True)

    # Load cached chunk metadata
    meta_path = os.path.join(LOGITS_DIR, 'chunks_meta.pt')
    if is_main:
        print(f'\nLoading chunk metadata from {meta_path}...', flush=True)
    meta = torch.load(meta_path, weights_only=False)
    n_chunks = len(meta['input_ids'])
    if is_main:
        print(f'  {n_chunks} chunks loaded', flush=True)

    # Verify logits exist
    n_logits = len([f for f in os.listdir(LOGITS_DIR) if f.endswith('.pt') and f != 'chunks_meta.pt'])
    if is_main:
        print(f'  {n_logits}/{n_chunks} teacher logit files found', flush=True)
    if n_logits < n_chunks:
        missing = [i for i in range(n_chunks) if not os.path.exists(os.path.join(LOGITS_DIR, f'{i}.pt'))]
        print(f'  WARNING: {len(missing)} logit files missing! First 10: {missing[:10]}', flush=True)

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(TEACHER_PATH, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    if SEP_TOKEN not in tokenizer.get_vocab():
        tokenizer.add_special_tokens({'additional_special_tokens': [SEP_TOKEN]})
    sep_token_id = tokenizer.convert_tokens_to_ids(SEP_TOKEN)

    # Load WMB eval sample
    wmb_records = []
    if os.path.exists(WMB_EVAL_PATH):
        with open(WMB_EVAL_PATH) as f:
            for line in f:
                wmb_records.append(json.loads(line))
        if is_main:
            print(f'  Loaded {len(wmb_records)} WMB eval pages', flush=True)

    # Split train/val
    rng = np.random.RandomState(SEED)
    indices = rng.permutation(n_chunks).tolist()
    val_size = min(args.val_chunks, n_chunks // 10)

    val_indices = indices[:val_size]
    train_indices = indices[val_size:]
    if is_main:
        print(f'\n  Train: {len(train_indices)} chunks', flush=True)
        print(f'  Val:   {len(val_indices)} chunks', flush=True)

    # Load student model
    if is_main:
        print(f'\nLoading student ({STUDENT_MODEL})...', flush=True)
    student_model = AutoModelForTokenClassification.from_pretrained(
        STUDENT_MODEL,
        num_labels=NUM_LABELS,
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        attn_implementation='sdpa',
    )
    student_model.resize_token_embeddings(len(tokenizer))

    if is_main:
        n_params = sum(p.numel() for p in student_model.parameters())
        print(f'  Student params: {n_params/1e6:.0f}M', flush=True)

    pad_token_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id

    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size * 2,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        weight_decay=0.01,
        warmup_ratio=0.1,
        eval_strategy='steps',
        eval_steps=0.25,
        save_strategy='steps',
        save_steps=0.25,
        load_best_model_at_end=True,
        metric_for_best_model='f1',
        greater_is_better=True,
        logging_steps=50,
        bf16=True,
        gradient_checkpointing=True,
        dataloader_num_workers=4,
        remove_unused_columns=False,
        report_to='none',
        ddp_find_unused_parameters=False,
    )

    callbacks = []
    if wmb_records:
        callbacks.append(RougeEvalCallback(tokenizer, sep_token_id, wmb_records))

    trainer = DistillTrainer(
        alpha=args.alpha,
        temperature=args.temperature,
        model=student_model,
        args=training_args,
        train_dataset=DistillDataset(train_indices, meta, LOGITS_DIR),
        eval_dataset=DistillDataset(val_indices, meta, LOGITS_DIR),
        data_collator=DistillCollator(pad_token_id),
        compute_metrics=compute_metrics,
        callbacks=callbacks,
    )

    if is_main:
        print('\nTraining...', flush=True)
    t0 = time.time()
    trainer.train()
    if is_main:
        print(f'\nTraining took {time.time() - t0:.0f}s', flush=True)

    # Final eval
    if is_main:
        print('\nFinal evaluation:', flush=True)
    metrics = trainer.evaluate()
    if is_main:
        for k, v in sorted(metrics.items()):
            print(f'  {k}: {v}', flush=True)

    # Save
    if is_main:
        trainer.save_model(os.path.join(OUTPUT_DIR, 'final'))
        tokenizer.save_pretrained(os.path.join(OUTPUT_DIR, 'final'))
        print(f'\nModel saved to {OUTPUT_DIR}/final', flush=True)


if __name__ == '__main__':
    main()
